[package]
name = "three_body"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13"
kiss3d = "0.32"
parry3d-f64 = "0.9.0"
rapier3d-f64 = "0.14.0"
serde = "1.0"
