constants:
  time_step: 0.01

universe:
  grav_const: 1.0
  bodies:
    - mass: 100.0
      position:
        x: 3.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 3.0
        z: 0.0
    - mass: 100.0
      position:
        x: -3.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: -3.0
        z: 0.0
    - mass: 10.0
      position:
        x: 10.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: -5.0
        z: 0.0
