constants:
  time_step: 0.1
  grav_const: 1.0
  duration: 1.0

universe:
  bodies:
    - mass: 1.0
      position:
        x: 1.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 1.0
        z: 0.0
    - mass: 1.0
      position:
        x: -1.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: -1.0
        z: 0.0
    - mass: 1.0
      position:
        x: 0.0
        y: -2.0
        z: 0.0
      velocity:
        x: 0.5
        y: 0.0
        z: 0.0
