constants:
  time_step: 0.01

universe:
  grav_const: 1.0
  bodies:
    - mass: 1.0
      position:
        x: -2.0
        y: -1.5
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.2
    - mass: 1.0
      position:
        x: -2.0
        y: 1.5
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: -0.1
    - mass: 1.0
      position:
        x: 2.0
        y: -1.5
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: -0.1
