constants:
  time_step: 0.01

universe:
  grav_const: 5.0
  bodies:
    - mass: 100.0
      position:
        x: 20.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 5.0
        z: -2.5
    - mass: 100.0
      position:
        x: -20.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: -5.0
        z: -2.5
    - mass: 100.0
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: 5.0
