constants:
  time_step: 0.001

universe:
  grav_const: 1.0
  bodies:
    - mass: 1.0
      position:
        x: 0.0
        y: 0.57735
        z: 0.0
      velocity:
        x: 1.0
        y: 0.0
        z: -0.01
    - mass: 1.0
      position:
        x: 0.5
        y: -0.288675
        z: 0.0
      velocity:
        x: -0.5
        y: -0.8660254
        z: -0.01
    - mass: 1.0
      position:
        x: -0.5
        y: -0.288675
        z: 0.0
      velocity:
        x: -0.5
        y: 0.8660254
        z: 0.02
