universe:
  grav_const: 20.0
  bodies:
    - mass: 100.0
      position:
        x: 20.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 8.0
        z: -5.0
    - mass: 100.0
      position:
        x: -20.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: -8.0
        z: -5.0
    - mass: 100.0
      position:
        x: 0.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: 10.0
