constants:
  time_step: 0.01

universe:
  grav_const: 0.5
  bodies:
    - mass: 200.0
      position:
        x: 3.0
        y: 0.0
        z: 0.0
      velocity:
        x: 0.0
        y: 0.0
        z: 0.0
    - mass: 200.0
      position:
        x: 0.0
        y: 4.0
        z: 0.0
      velocity:
        x: -5.0
        y: 0.0
        z: 0.0
    - mass: 200.0
      position:
        x: 0.0
        y: 0.0
        z: 5.0
      velocity:
        x: 5.0
        y: 0.0
        z: 0.0
